/**
 * Creates minimal UserData placeholder for SSM bootstrap
 * The actual MIAB setup will be done via SSM RunCommand after instance launch
 */
export function createBootstrapPlaceholderUserData(
  domainName: string,
  instanceDns: string,
  stackName: string,
  region: string
): string[] {
  return [
    '#!/bin/bash',
    'set -euxo pipefail',
    `echo "=========================================="`,
    `echo "Mail Server Instance Bootstrap Placeholder"`,
    `echo "Domain: ${domainName}"`,
    `echo "Instance DNS: ${instanceDns}.${domainName}"`,
    `echo "Stack: ${stackName}"`,
    `echo "Region: ${region}"`,
    `echo "=========================================="`,
    `echo ""`,
    `echo "This instance is ready for SSM-based bootstrap."`,
    `echo "Run the bootstrap command to configure Mail-in-a-Box:"`,
    `echo "  pnpm nx run ops-runner:instance:bootstrap -- --domain ${domainName}"`,
    `echo ""`,
    `echo "Preparing instance for bootstrap..."`,
    `# Install AWS CLI if not present (needed for SSM and bootstrap script)`,
    `if ! command -v aws >/dev/null 2>&1; then`,
    `  echo "Installing AWS CLI..."`,
    `  apt-get update -qq`,
    `  apt-get install -y curl unzip jq`,
    `  curl -sSL "https://awscli.amazonaws.com/awscli-exe-linux-\$(uname -m).zip" -o /tmp/awscliv2.zip`,
    `  unzip -q /tmp/awscliv2.zip -d /tmp`,
    `  /tmp/aws/install`,
    `  rm -rf /tmp/awscliv2.zip /tmp/aws`,
    `fi`,
    `# Install and configure SSM agent (required for Systems Manager)`,
    `if ! command -v amazon-ssm-agent >/dev/null 2>&1; then`,
    `  echo "SSM agent not found, installing via snap..."`,
    `  snap install amazon-ssm-agent --classic || {`,
    `    # Fallback: try apt installation for older Ubuntu versions`,
    `    echo "Snap install failed, trying apt installation..."`,
    `    apt-get update -qq`,
    `    apt-get install -y amazon-ssm-agent || true`,
    `  }`,
    `fi`,
    `# Ensure SSM agent is enabled and started`,
    `systemctl enable amazon-ssm-agent || true`,
    `systemctl restart amazon-ssm-agent || true`,
    `# Wait a moment for agent to initialize`,
    `sleep 2`,
    `# Verify agent is running`,
    `if systemctl is-active --quiet amazon-ssm-agent; then`,
    `  echo "✅ SSM agent is running"`,
    `else`,
    `  echo "⚠️  SSM agent may not be running - check IAM role has AmazonSSMManagedInstanceCore policy"`,
    `  systemctl status amazon-ssm-agent || true`,
    `fi`,
    `echo "Instance ready for bootstrap at: $(date)"`,
    `echo "=========================================="`,
  ];
}
