#!/usr/bin/env node

/**
 * Clean and Regenerate Script - Cross-Platform Node.js Version
 *
 * This script removes the folders generated by the three generation scripts
 * and then executes them concurrently.
 *
 * Generated folders:
 * - extracted-codebase/ (from generate_master_codebase.sh)
 * - extracted-configs/ (from generate_master_config.sh)
 * - extracted-rules/ (from generate_master_rules.sh)
 *
 * Usage:
 *   tsx scripts/clean-and-regenerate.ts
 *   or
 *   node --loader tsx scripts/clean-and-regenerate.ts
 */

import { spawn, exec } from 'child_process';
import { existsSync, rmSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const ROOT_DIR = join(__dirname, '..');

interface ScriptProcess {
  name: string;
  process: ReturnType<typeof spawn>;
}

async function cleanGeneratedFolders(): Promise<void> {
  console.log('🧹 Cleaning generated folders...');
  console.log(`Root directory: ${ROOT_DIR}`);

  const foldersToRemove = [
    'extracted-codebase',
    'extracted-configs',
    'extracted-rules'
  ];

  for (const folder of foldersToRemove) {
    const folderPath = join(ROOT_DIR, folder);
    if (existsSync(folderPath)) {
      console.log(`Removing ${folderPath}`);
      rmSync(folderPath, { recursive: true, force: true });
    } else {
      console.log(`Folder ${folderPath} does not exist, skipping`);
    }
  }

  console.log('✅ Clean complete');
  console.log();
}

function runScript(scriptName: string): Promise<{ name: string; code: number | null; signal: NodeJS.Signals | null }> {
  return new Promise((resolve, reject) => {
    const scriptPath = join(__dirname, scriptName);
    const command = `bash "${scriptPath}"`;

    const child = exec(command, {
      cwd: ROOT_DIR,
      env: process.env,
      maxBuffer: 1024 * 1024 * 10 // 10MB buffer for output
    }, (error, stdout, stderr) => {
      // Show progress from stdout
      if (stdout) {
        process.stdout.write(stdout);
      }

      // Show errors from stderr (but filter out non-critical warnings)
      if (stderr) {
        // Filter out common file-not-found warnings that are expected
        const filteredStderr = stderr
          .split('\n')
          .filter(line =>
            !line.includes('File not found:') ||
            (!line.includes('.eslintrc.cjs') &&
             !line.includes('.nvmrc') &&
             !line.includes('jest.config.mjs'))
          )
          .join('\n')
          .trim();

        if (filteredStderr) {
          process.stderr.write(filteredStderr + '\n');
        }
      }

      if (error) {
        reject(new Error(`${scriptName} failed: ${error.message}`));
        return;
      }

      resolve({ name: scriptName, code: 0, signal: null });
    });
  });
}

async function runGenerationScriptsConcurrently(): Promise<void> {
  console.log('🚀 Starting concurrent regeneration...');

  const scripts = [
    'generate_master_codebase.sh',
    'generate_master_config.sh',
    'generate_master_rules.sh'
  ];

  try {
    // Start all scripts concurrently with progress indicators
    const promises = scripts.map(script => {
      console.log(`Starting ${script}...`);
      return runScript(script);
    });

    console.log('All scripts started. Waiting for completion...');
    console.log();

    // Wait for all to complete
    await Promise.all(promises);

    console.log();
    console.log('🎉 All generation scripts completed successfully!');
    console.log('Generated folders:');
    console.log('  - extracted-codebase/');
    console.log('  - extracted-configs/');
    console.log('  - extracted-rules/');

  } catch (error) {
    console.error('❌ Error during script execution:', error);
    process.exit(1);
  }
}

async function main(): Promise<void> {
  try {
    await cleanGeneratedFolders();
    await runGenerationScriptsConcurrently();
  } catch (error) {
    console.error('❌ Script failed:', error);
    process.exit(1);
  }
}

// Handle process signals gracefully
process.on('SIGINT', () => {
  console.log('\n⚠️  Received SIGINT, exiting...');
  process.exit(130);
});

process.on('SIGTERM', () => {
  console.log('\n⚠️  Received SIGTERM, exiting...');
  process.exit(143);
});

main().catch((error) => {
  console.error('💥 Unhandled error:', error);
  process.exit(1);
});
