#!/usr/bin/env bash
set -euo pipefail
IFS=$'\n\t'

# Clean and Regenerate Script
# This script removes the folders generated by the three generation scripts
# and then executes them concurrently.
#
# Generated folders:
# - extracted-codebase/ (from generate_master_codebase.sh)
# - extracted-configs/ (from generate_master_config.sh)
# - extracted-rules/ (from generate_master_rules.sh)
#
# Usage:
#   ./scripts/clean-and-regenerate.sh

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SCRIPT_DIR="$ROOT_DIR/scripts"

echo "🧹 Cleaning generated folders..."
echo "Root directory: $ROOT_DIR"

# Remove the generated folders
folders_to_remove=(
    "$ROOT_DIR/extracted-codebase"
    "$ROOT_DIR/extracted-configs"
    "$ROOT_DIR/extracted-rules"
)

for folder in "${folders_to_remove[@]}"; do
    if [ -d "$folder" ]; then
        echo "Removing $folder"
        rm -rf "$folder"
    else
        echo "Folder $folder does not exist, skipping"
    fi
done

echo "✅ Clean complete"
echo
echo "🚀 Starting concurrent regeneration..."

# Start the generation scripts concurrently
echo "Starting generate_master_codebase.sh..."
"$SCRIPT_DIR/generate_master_codebase.sh" &
pid1=$!

echo "Starting generate_master_config.sh..."
"$SCRIPT_DIR/generate_master_config.sh" &
pid2=$!

echo "Starting generate_master_rules.sh..."
"$SCRIPT_DIR/generate_master_rules.sh" &
pid3=$!

echo "All scripts started. Waiting for completion..."
echo

# Wait for all background processes to complete
wait $pid1
wait $pid2
wait $pid3

echo
echo "🎉 All generation scripts completed successfully!"
echo "Generated folders:"
echo "  - extracted-codebase/"
echo "  - extracted-configs/"
echo "  - extracted-rules/"
