import type { ExtractorConfig } from './src/types';

// Default exclusions derived from workspace .gitignore.
// Policy: everything ignored by git is excluded from extraction unless explicitly included.
const gitignoreBasedExcludeDirs = [
  'dist',
  'tmp',
  'out-tsc',
  'node_modules',
  '.idea',
  '.c9',
  '.settings',
  '.sass-cache',
  'coverage',
  'typings',
  '.nx',
] as const;

// Additional exclusions not covered by .gitignore, focused on lean AI context exports.
const additionalExcludeDirs = [
  'build',
  '.next',
  '.turbo',
  '.cache',
  'cdk.out',
  '.git',
  '.vscode',
  'temp',
  'reports',
  '.pnpm-store',
  'test-results',
  '__pycache__',
  '.pytest_cache',
  '.venv',
  'venv',
  '.aws',
  '.ssh',
  '.secrets',
  '.history',
  'archive',
  'Archive',
  'runs',
  'exports',
  'output',
  'data',
  'extracted-archive',
  'extracted-codebase',
  'extracted-configs',
  'extracted-rules',
  'monitoring-reports',
  'webmail-logs',
] as const;

const gitignoreBasedExcludeFilePathRegexSources = [
  '(^|\\/)\\.project$',
  '(^|\\/)\\.classpath$',
  '\\.launch$',
  '\\.sublime-workspace$',
  '(^|\\/)connect\\.lock$',
  '(^|\\/)libpeerconnection\\.log$',
  '(^|\\/)npm-debug\\.log$',
  '(^|\\/)yarn-error\\.log$',
  '(^|\\/)testem\\.log$',
  '(^|\\/)\\.DS_Store$',
  '(^|\\/)Thumbs\\.db$',
  '(^|\\/)\\.claude\\/settings\\.local\\.json$',
  '(^|\\/)\\.claude\\/worktrees\\/',
  '(^|\\/)runs\\/site-audits\\/(?!\\.gitkeep$)',
] as const;

const additionalExcludeFilePathRegexSources = [
  '\\.map$',
  '\\.min\\.',
  '\\.chunk\\.',
  '(^|\\/)(pnpm-lock\\.yaml|yarn\\.lock|package-lock\\.json|bun\\.lockb)($|\\/)',
  '(^|\\/)(.*\\.tsbuildinfo)($|\\/)',
  '(^|\\/)exports\\/',
  '(^|\\/)reports\\/',
  '(^|\\/)coverage\\/',
  '(^|\\/)dist\\/',
  '(^|\\/)build\\/',
  '(^|\\/)cdk\\.out\\/',
  '(^|\\/)node_modules\\/',
  '(^|\\/)\\.pnpm-store\\/',
  '(^|\\/)\\.next\\/',
  '(^|\\/)\\.turbo\\/',
  '(^|\\/)\\.cache\\/',
  '(^|\\/)\\.output\\/',
  '(^|\\/)out\\/',
  '(^|\\/)tmp\\/',
  '(^|\\/)temp\\/',
  '(^|\\/)test-results\\/',
  '(^|\\/)playwright-report\\/',
  '(^|\\/)storybook-static\\/',
  '\\.generated\\.(ts|tsx|js|jsx|mjs|cjs|json)$',
  '\\.gen\\.(ts|tsx|js|jsx|mjs|cjs|json)$',
  '(^|\\/)(generated|__generated__|gen|artifacts|storybook-static)(\\/|$)',
  '\\.snap$',
  '(^|\\/)(\\.eslintcache|\\.tsbuildinfo)$',
  '(^|\\/)\\.cursor\\/cursor-experiments\\/',
  '(^|\\/)\\.cursor\\/plans\\/',
  '(^|\\/)\\.foundry\\/staging\\/',
  '(^|\\/)apps\\/outbound-emails\\/first-contact\\/dist\\/',
  '(^|\\/)archive\\/',
  '(^|\\/)Archive\\/',
  '(^|\\/)runs\\/',
  '(^|\\/)output\\/',
  '(^|\\/)data\\/',
  '(^|\\/)extracted-(archive|codebase|configs|rules)\\/',
  '(^|\\/)webmail-logs\\/',
  '(^|\\/)monitoring-reports\\/',
  // Sensitive local config, credentials, and key material
  '(^|\\/)(\\.env|\\.env\\..+)$',
  '(^|\\/)(\\.npmrc|\\.pypirc|\\.netrc)$',
  '(^|\\/)(id_rsa|id_dsa|id_ecdsa|id_ed25519)(\\.pub)?$',
  '\\.(pem|p12|pfx|key|crt|cer|der|jks|keystore)$',
  '(^|\\/)(credentials|credential|secrets?|tokens?)(\\.|\\/|$)',
  '(^|\\/)([aA][wW][sS]-?)?([cC][rR][eE][dD][eE][nN][tT][iI][aA][lL][sS]|[cC][oO][nN][fF][iI][gG])\\.json$',
] as const;

const fullRepoContextConfig: ExtractorConfig = {
  version: '1.1.0',
  includedRoots: ['.'],
  includedFiles: [
    'AGENTS.md',
    'README.md',
    'CONTRIBUTING.md',
    'CODE_OF_CONDUCT.md',
    'LICENSE',
    '.env.example',
    '.gitignore',
    'DEPLOYMENT.md',
    'jest.config.ts',
    'jest.preset.js',
    'nx',
    'nx.bat',
    'nx.json',
    'opencode.json',
    'package.json',
    'package.engines.json',
    'tsconfig.base.json',
    'vitest.workspace.ts',
  ],
  outputPath: 'exports/professional-monorepo-full-repo-ai-context.txt',
  includeExtensions: [
    '.ts',
    '.tsx',
    '.js',
    '.jsx',
    '.mjs',
    '.cjs',
    '.json',
    '.yaml',
    '.yml',
    '.toml',
    '.md',
    '.mdx',
    '.sh',
    '.bash',
    '.py',
    '.txt',
    '.sql',
    '.graphql',
    '.gql',
    '.bat',
  ],
  includeFileNames: ['Dockerfile', '.env.example', 'nx', 'nx.bat'],
  includeFilePathRegexSources: [
    '^.*\\/pnpm-workspace\\.yaml$',
    '^.*\\/package\\.json$',
    '^.*\\/project\\.json$',
    '^.*\\/nx\\.json$',
    '^.*\\/eslint\\.config\\.(mjs|js|cjs)$',
    '^.*\\/vitest\\.config\\.(ts|js|mjs|cjs)$',
    '^.*\\/playwright\\.config\\.(ts|js|mjs|cjs)$',
    '^.*\\/tsconfig(\\..*)?\\.json$',
    '^.*\\/Dockerfile$',
  ],
  excludeDirs: [...gitignoreBasedExcludeDirs, ...additionalExcludeDirs],
  excludeFilePathRegexSources: [
    ...gitignoreBasedExcludeFilePathRegexSources,
    ...additionalExcludeFilePathRegexSources,
  ],
};

export default fullRepoContextConfig;

